   
   log_level: INFO
accounts:
- id: example-account1
  driver: rubykube
  debug: false
  host: "https://www.brandlovers.co.za"
  ws: "wss://www.brandlovers.co.za"
  key: "fa45a30e94b1eb1c"
  secret: "6dfdb515791ef72a4e24dae497ae925f"
  delay: 0.75

- id: example-account2
  driver: bitfinex
  debug: false
  host: "api.bitfinex.com"
  key: "GGMcaLoDdl128x0KMFDzGLptLFlKCh39JRlE9r7vNPf"
  secret: "ZcfHsJKzUV8JwtNYg82OQ9QgMvzYjraT1DSki8mMwoM"
  delay: 1
  
strategies:
- id: ETHUSD-orderback
  type: orderback
  debug: false
  enabled: true
  period: 90
  params:
    spread_bids: 0.005
    spread_asks: 0.005
    limit_asks_base: 10
    limit_bids_base: 10
    levels_size: 0.5
    levels_count: 5
    side: both
    enable_orderback: false
    min_order_back_amount: 0.0002

  target:
    account_id: example-account1
    market_id: ETHUSD

  sources:
  - account_id: example-account2
    market_id: ETHUSD

- id: BTCUSDT-micro
  type: microtrades
  debug: false
  period: 30
  period_random_delay: 30
  enabled: false
  params:
    linked_strategy_id: ETHUSD-orderback
    min_amount: 0.0001
    max_amount: 0.01
    min_price: 170
    max_price: 230

  target:
    account_id: example-account2
    market_id: ETHUSD

