strategy:
  type: copy
  volume_ratio: 0.1
  target:
    driver: rubykube
    market: 'ETHUSD'
    host: "https://www.brandlovers.co.za/"
    key: "70fc75debb075551"
    secret: "5c2b3e6cea85f02524ac12283c8e9cb0"
    rate_limit: 1
  sources:
    - driver: bitfinex
      market: 'ETHUSD'
      host: "api.bitfinex.com"
      key: "GGMcaLoDdl128x0KMFDzGLptLFlKCh39JRlE9r7vNPf"
      secret: "ZcfHsJKzUV8JwtNYg82OQ9QgMvzYjraT1DSki8mMwoM"
      rate_limit: 0.2
